### PR TITLE
initialize github workflow, update install_requires accordingly

### PR DESCRIPTION
**Pull request by ngoan1608**

### CODE REVIEW

**Review by test-fullautomation — APPROVED** [review]
Hi  Ngoan,
looks good to me!
Thank you,
 Thomas

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Ngoan,
please solve the merge conflict.
Thank you,
 Thomas

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Ngoan,
please solve the merge conflict.
Thank you,
 Thomas

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Ngoan,
please support with the merge confilct.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @ngoan1608 ,
can you please solve the merge conflict. I would merge the pull-request immediately.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

I did not notice about this PR until you mentioned me.
I have just solved the conflict.

Thank you,
Ngoan

**Review by test-fullautomation — APPROVED** [review]

**Pull request merged**
